SELECT * FROM products;
SELECT id FROM products;
SELECT id AS product_id, is_sale AS on_sale FROM products;
SELECT * FROM products WHERE id = 10;
SELECT id, name FROM products WHERE id = 10;
SELECT id as my_id, name AS product_name FROM products WHERE id >=10;
SELECT * FROM products WHERE name = 'TV';
SELECT * FROM products WHERE is_sale != false;
SELECT * FROM products WHERE inventory != 0 AND price > 20;
SELECT * FROM products WHERE name LIKE 'TV%';
SELECT * FROM products WHERE name NOT LIKE '%en%';
